/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinhaPalavra;

import javax.swing.JPanel;

/**
 *
 * @author wrkerber
 */
public class Tela extends javax.swing.JFrame 
{

    /**
     * Creates new form TelaPrincipal
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPalavra = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jLabelTaxaCruzamento = new javax.swing.JLabel();
        jButtonParar = new javax.swing.JButton();
        jLabelTaxaMutacao = new javax.swing.JLabel();
        jLabelUtilizaElitismo = new javax.swing.JLabel();
        jLabelTamanhoPopulacao = new javax.swing.JLabel();
        jLabelNumeroMaximoGeracoes = new javax.swing.JLabel();
        jTaxaCruzamento = new javax.swing.JTextField();
        jTaxaMutacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLogs = new javax.swing.JTextArea();
        jTamanhoPopulacao = new javax.swing.JTextField();
        jNumeroMaximoGeracoes = new javax.swing.JTextField();
        jLabelPalavra = new javax.swing.JLabel();
        jRadioButtonUtilizaElitismo = new javax.swing.JRadioButton();
        jLabelModoDebug = new javax.swing.JLabel();
        jRadioButtonModoDebug = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPalavra.setText("Teste Palavra");

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabelTaxaCruzamento.setText("Taxa de Cruzamento (%):");

        jButtonParar.setText("Parar");

        jLabelTaxaMutacao.setText("Taxa de Mutação (%):");

        jLabelUtilizaElitismo.setText("Utilizar Elitismo:");

        jLabelTamanhoPopulacao.setText("Tamanho da População:");

        jLabelNumeroMaximoGeracoes.setText("Número Máximo de Gerações:");

        jTaxaCruzamento.setText("60");

        jTaxaMutacao.setText("30");
        jTaxaMutacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxaMutacaoActionPerformed(evt);
            }
        });

        jTextAreaLogs.setColumns(20);
        jTextAreaLogs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLogs);

        jTamanhoPopulacao.setText("100");

        jNumeroMaximoGeracoes.setText("1000");

        jLabelPalavra.setText("Palavra:");

        jRadioButtonUtilizaElitismo.setSelected(true);
        jRadioButtonUtilizaElitismo.setText("Sim");

        jLabelModoDebug.setText("Modo debug:");

        jRadioButtonModoDebug.setText("Sim");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonParar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTamanhoPopulacao)
                            .addComponent(jLabelUtilizaElitismo)
                            .addComponent(jLabelNumeroMaximoGeracoes)
                            .addComponent(jLabelTaxaMutacao)
                            .addComponent(jLabelTaxaCruzamento)
                            .addComponent(jLabelPalavra)
                            .addComponent(jLabelModoDebug))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonModoDebug)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTaxaCruzamento, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jNumeroMaximoGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonUtilizaElitismo)
                                    .addComponent(jTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPalavra)
                            .addComponent(jPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTaxaCruzamento)
                            .addComponent(jTaxaCruzamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTaxaMutacao)
                            .addComponent(jTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUtilizaElitismo)
                            .addComponent(jRadioButtonUtilizaElitismo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTamanhoPopulacao)
                            .addComponent(jTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroMaximoGeracoes)
                            .addComponent(jNumeroMaximoGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModoDebug)
                            .addComponent(jRadioButtonModoDebug))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIniciar)
                            .addComponent(jButtonParar)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        jTextAreaLogs.setText("");
        int contModoDebug = 0;

        //Define a solução
        Algoritimo.setSolucao(jPalavra.getText());
        //Define os caracteres existentes
        Algoritimo.setCaracteres("!,.:;?áÁãÃâÂõÕôÔóÓéêÉÊíQWERTYUIOPASDFGHJKLÇZXCVBNMqwertyuiopasdfghjklçzxcvbnm1234567890 ");
        //taxa de crossover de 60%
        Algoritimo.setTaxaDeCrossover(Double.parseDouble(jTaxaCruzamento.getText()));
        //taxa de mutação de 3%
        Algoritimo.setTaxaDeMutacao(Double.parseDouble(jTaxaMutacao.getText()));
        //elitismo
        boolean elitismo = jRadioButtonUtilizaElitismo.isSelected();
        //tamanho da população
        int tamPop = Integer.parseInt(jTamanhoPopulacao.getText());
        //numero máximo de gerações
        int numMaxGeracoes = Integer.parseInt(jNumeroMaximoGeracoes.getText());
        
        boolean modeDebug = jRadioButtonModoDebug.isSelected();

        //define o número de genes do indivíduo baseado na solução
        int numGenes = Algoritimo.getSolucao().length();
        if (modeDebug)
        {
            jTextAreaLogs.append("1 - Define o número de genes do indivíduo. Neste caso o número de caracteres: "+Algoritimo.getSolucao().length()+"\n");
        }

        //cria a primeira população aleatérioa
        if (modeDebug)
        {
            jTextAreaLogs.append("2 - Criação da primeira população aleatória \n");
        }
        Populacao populacao = new Populacao(numGenes, tamPop);
        if (modeDebug)
        {
            jTextAreaLogs.append("3 - Foi criado uma população de "+tamPop+" indivíduos conforme configurado. Segue exemplos de indivíduos \n");
            int j = tamPop / 10;
            for (int i = 0; i < j; i++) 
            {
                jTextAreaLogs.append("    "+populacao.getIndivduo(i).getGenes()+" \n");
            }
        }
        boolean temSolucao = false;
        int geracao = 0;
        
        jTextAreaLogs.append("Iniciando... Aptidão da solução: "+Algoritimo.getSolucao().length()+"\n");
        //System.out.println("Iniciando... Aptidão da solução: "+Algoritimo.getSolucao().length());
        
        //loop até o critério de parada
        if (modeDebug)
        {
            jTextAreaLogs.append("4 - Neste momento entra em um loop, onde só vai sair quando chegar no resultado ou atingir o número máximo de gerações que é "+numMaxGeracoes+" \n");
            contModoDebug = 0;
        }
        while (!temSolucao && geracao < numMaxGeracoes) 
        {    
            geracao++;

            //cria nova populacao
            populacao = Algoritimo.novaGeracao(populacao, elitismo);
            if (modeDebug)
            {
                jTextAreaLogs.append("5 - Cria uma nova população. Exemplos: \n");
                int j = tamPop / 10;
                for (int i = 0; i < j; i++) 
                {
                    jTextAreaLogs.append("    "+populacao.getIndivduo(i).getGenes()+" \n");
                }
            }

            jTextAreaLogs.append("Geração " + geracao + " | Aptidão: " + populacao.getIndivduo(0).getAptidao() + " | Melhor: " + populacao.getIndivduo(0).getGenes()+"\n");
            //System.out.println("Geração " + geracao + " | Aptidão: " + populacao.getIndivduo(0).getAptidao() + " | Melhor: " + populacao.getIndivduo(0).getGenes());
            
            //verifica se tem a solucao
            if (modeDebug)
            {
                jTextAreaLogs.append("6 - Verifica se tem a solução, fazendo um for, comparando se a string (usnado equals) da solução é igual a string do indivíduo. \n");
            }
            
            temSolucao = populacao.temSolocao(Algoritimo.getSolucao());
        }

        if (geracao == numMaxGeracoes) {
            jTextAreaLogs.append("Número Maximo de Gerações | " + populacao.getIndivduo(0).getGenes() + " " + populacao.getIndivduo(0).getAptidao()+"\n");
        }

        if (temSolucao) {
            jTextAreaLogs.append("Encontrado resultado na geração " + geracao + " | " + populacao.getIndivduo(0).getGenes() + " (Aptidão: " + populacao.getIndivduo(0).getAptidao() + ") \n");
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTaxaMutacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxaMutacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxaMutacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JLabel jLabelModoDebug;
    private javax.swing.JLabel jLabelNumeroMaximoGeracoes;
    private javax.swing.JLabel jLabelPalavra;
    private javax.swing.JLabel jLabelTamanhoPopulacao;
    private javax.swing.JLabel jLabelTaxaCruzamento;
    private javax.swing.JLabel jLabelTaxaMutacao;
    private javax.swing.JLabel jLabelUtilizaElitismo;
    private javax.swing.JTextField jNumeroMaximoGeracoes;
    private javax.swing.JTextField jPalavra;
    private javax.swing.JRadioButton jRadioButtonModoDebug;
    private javax.swing.JRadioButton jRadioButtonUtilizaElitismo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTamanhoPopulacao;
    private javax.swing.JTextField jTaxaCruzamento;
    private javax.swing.JTextField jTaxaMutacao;
    private javax.swing.JTextArea jTextAreaLogs;
    // End of variables declaration//GEN-END:variables
}
